<h2>JSON API pro&nbsp;zjišťování cen MtG karet</h2>

<p>Nabízíme Vám možnost získavat data o&nbsp;jednotlivých kartách automatizovaně pomocí našeho JSON API.</p>

<p>Pro&nbsp;usnadnění propojení jsme pro&nbsp;Vás také připravili malou PHP knihovnu, která má jednoduché rozhraní a
její začlenění zvládne i&nbsp;programátor začátečník.</p>

<p>Dokumentace k&nbsp;oběma knihovnách jsou ke&nbsp;stažení zde:</p>

<p class="ui-mini" >
    <a class="ui-btn ui-btn-icon-left ui-icon-action ui-corner-all"
       href="<?php echo $this->baseUrl('/download/mtgim-json-api-1_0.pdf') ?>"
       data-ajax="false"
        >
        Dokumentace JSON API
    </a>
</p>
<p class="ui-mini" >
    <a class="ui-btn ui-btn-icon-left ui-icon-action ui-corner-all"
       href="<?php echo $this->baseUrl('/download/mtgim-json-lib-1_0.pdf') ?>"
       data-ajax="false"
        >
        PHP Klient pro JSON API
    </a>
</p>

<p>Pokud máte zájem o&nbsp;zřízení účtu pro&nbsp;JSON API, nebo i&nbsp;o&nbsp;PHP knihovnu, kontaktujte nás pomocí kontaktního formuláře.</p>
<p>
    <a class="ui-btn ui-btn-icon-left ui-icon-edit ui-corner-all"
       href="<?php echo $this->baseUrl('/index/contact') ?>"
       data-transition="slide"
        >
        Kontaktovat
    </a>
</p>

<p>Za&nbsp;přístup k&nbsp;API účtujeme měsíční poplatek, který se liší v&nbsp;závislosti na&nbsp;předpokládaném
    maximálním zatížení. (Počtu dotazů na&nbsp;API za&nbsp;den.)</p>
<p>Cena za poskytnutí PHP knihovny je <strong>200 Kč</strong>.</p>
