<h2>Novinky</h2>

<div class="ui-body ui-body-a">
    <h4>Verze 1.2.6</h4>
    <p><strong>Datum:</strong> 23.10.2014</p>
    <p>Upraveny texty v aplikaci</p>
    <p>Minimalizace JS a CSS. Nově aplikace načítá jen jeden CSS a JS soubor
        (pro netechniky = načítá se to rychleji).
    </p>
</div>

<div class="ui-body ui-body-a">
    <h4>Verze 1.2.5</h4>
    <p><strong>Datum:</strong> 17.10.2014</p>
    <p>Možnost skrytí novinek na úvodní stránce. Nové novinky se zobrazí opět s novou verzí.</p>
    <p>Do navigace přidána sekce "Novinky".</p>
</div>

<div class="ui-body ui-body-a">
    <h4>Verze 1.2.4</h4>
    <p><strong>Datum:</strong> 15.10.2014</p>
    <p>Možnost uložení formuláře jako vyhledávače v prohlížeči.</p>
    <p>Možnost odkazování na výsledek hledání přes URL.</p>
    <p>Upravení vzhledu pro větší displaye.</p>
    <p>Doplněny podmínky používání webu.</p>
    <p>Klávesová zkratka pro přechod do vyhledávacího pole.</p>
    <p>Více o novinkách v&nbsp;sekci <a href="<?php echo $this->baseUrl('/info/tips') ?>">tipy a triky</a>.</p>
</div>

<div class="ui-body ui-body-a">
    <h4>Verze 1.2.3</h4>
    <p><strong>Datum:</strong> 2.10.2014</p>
    <p>Vylepšení trackování přes GA. MtGiM JSON API.</p>
</div>

<div class="ui-body ui-body-a">
    <h4>Verze 1.2.2</h4>
    <p><strong>Datum:</strong> 26.7.2014</p>
    <p>Vylepšeno zobrazování edic pro e-shop Černý Rytíř. Zaveden changelog. Drobné grafické opravy.</p>
</div>

<div class="ui-body ui-body-a">
    <h4>Verze 1.2.0</h4>
    <p><strong>Datum:</strong> 18.7.2014</p>
    <p>Přidána možnost zobrazit obrázek karty.</p>
</div>

<div class="ui-body ui-body-a">
    <h4>Verze 1.1.2</h4>
    <p><strong>Datum:</strong> 10.7.2014</p>
    <p>Přidáno vyhledávání v obchodě rishada.cz.</p>
</div>

<div class="ui-body ui-body-a">
    <h4>Verze 1.1.0</h4>
    <p><strong>Datum:</strong> 2.7.2014</p>
    <p>Přidáno vyhledávání v dalších obchodech. Konkrétně mysticshop.cz a najda.cz.</p>
</div>

<div class="ui-body ui-body-a">
    <h4>Verze 1.0.4</h4>
    <p><strong>Datum:</strong> 12.6.2014</p>
    <p>Pouze bugfixy.</p>
</div>

<div class="ui-body ui-body-a">
    <h4>Verze 1.0.0</h4>
    <p><strong>Datum:</strong> 2.6.2014</p>
    <p>První ostrá verze aplikace.</p>
</div>
