<h2>Novinky</h2>

<div class="ui-body ui-body-a ui-corner-all">
    <table>
        <tr>
            <th>Datum</th>
            <th>Verze</th>
            <th>Novinky</th>
        </tr>
        <tr>
            <td>17.10.2014</td>
            <td>1.2.5</td>
            <td><ul>
                    <li>Možnost skrytí novinek na úvodní stránce. Nové novinky se zobrazí opět s novou verzí.</li>
                    <li>Do navigace přidána sekce "Novinky".</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>15.10.2014</td>
            <td>1.2.4</td>
            <td>
                <ul>
                    <li>Možnost uložení formuláře jako vyhledávače v prohlížeči.</li>
                    <li>Možnost odkazování na výsledek hledání přes URL.</li>
                    <li>Upravení vzhledu pro větší displaye.</li>
                    <li>Doplněny podmínky používání webu.</li>
                    <li>Klávesová zkratka pro přechod do vyhledávacího pole.</li>
                </ul>
                Více o novinkách v&nbsp;sekci <a href="<?php echo $this->baseUrl('/info/tips') ?>">tipy a triky</a>.
            </td>
        </tr>
        <tr>
            <td>2.10.2014</td>
            <td>1.2.3</td>
            <td>Vylepšení trackování přes GA. MtGiM JSON API.</td>
        </tr>
        <tr>
            <td>26.7.2014</td>
            <td>1.2.2</td>
            <td>Vylepšeno zobrazování edic pro e-shop Černý Rytíř. Zaveden changelog. Drobné grafické opravy.</td>
        </tr>
        <tr>
            <td>18.7.2014</td>
            <td>1.2.0</td>
            <td>Přidána možnost zobrazit obrázek karty.</td>
        </tr>
        <tr>
            <td>10.7.2014</td>
            <td>1.1.2</td>
            <td>Přidáno vyhledávání v obchodě rishada.cz.</td>
        </tr>
        <tr>
            <td>2.7.2014</td>
            <td>1.1.0</td>
            <td>Přidáno vyhledávání v dalších obchodech. Konkrétně mysticshop.cz a najda.cz.</td>
        </tr>
        <tr>
            <td>12.6.2014</td>
            <td>1.0.4</td>
            <td>Pouze bugfixy.</td>
        </tr>
        <tr>
            <td>2.6.2014</td>
            <td>1.0.0</td>
            <td>První ostrá verze aplikace.</td>
        </tr>
    </table>
</div>