<h2>Novinky</h2>


<div class="ui-body ui-body-a">
    <h3>Verze 1.2.12</h3>
    <p><strong>Datum:</strong> 19.8.2015</p>
    <p>Upraveno rozložení úvodní stránky.</p>
    <p>Zobrazování náhledů pro obchod Černý Rytíř vylepšeno.</p>
</div>

<div class="ui-body ui-body-a">
    <h3>Verze 1.2.11</h3>
    <p><strong>Datum:</strong> 12.3.2015</p>
    <p>
        Změna načítání náhledů karet. Namísto projektu <a href="http://mtgimage.com">mtgimage.com</a> jsou obrázky
        karet získávány ze&nbsp;stránek <a href="http://gatherer.wizards.com">gatherer.wizards.com</a>.
    </p>
    <p>
        Bohužel se nejedná o&nbsp;změnu k lepšímu. Obrázky jsou v horší kvalitě a zatím je možné získat jen obrázek
        prvního vydání karty. Tzn. ne obrázek dané edice.
    </p>
</div>

<div class="ui-body ui-body-a">
    <h3>Verze 1.2.10</h3>
    <p><strong>Datum:</strong> 12.3.2015</p>
    <p>Zrušení zobrazování náhledů karet z důvodu ukončení činnosti projetku <a href="http://mtgimage.com">mtgimage.com</a>.</p>
</div>

<div class="ui-body ui-body-a">
    <h3>Verze 1.2.9</h3>
    <p><strong>Datum:</strong> 9.2.2015</p>
    <p>SEO optimalizace;</p>
</div>

<div class="ui-body ui-body-a">
    <h3>Verze 1.2.8</h3>
    <p><strong>Datum:</strong> 1.2.2015</p>
    <p>
        Oprava zobrazování náhledu obrázku karty. Karta se nově vždy vejde na&nbsp;jednu obrazovaku zařízení. Nově by také
        zobrazení náhledu nemělo rozbít zobrazení výsledků hledání.
    </p>
</div>

<div class="ui-body ui-body-a">
    <h3>Verze 1.2.7</h3>
    <p><strong>Datum:</strong> 31.1.2015</p>
    <p>Upraveny texty v aplikaci.</p>
    <p>Uveřejněno API pro získávání dat o cenách karet.</p>
</div>

<div class="ui-body ui-body-a">
    <h3>Verze 1.2.6</h3>
    <p><strong>Datum:</strong> 29.1.2014</p>
    <p>Upraveny texty v aplikaci.</p>
    <p>Minimalizace JS a CSS. Nově aplikace načítá jen jeden CSS a JS soubor
        (pro netechniky = načítá se to rychleji).
    </p>
</div>

<div class="ui-body ui-body-a">
    <h3>Verze 1.2.5</h3>
    <p><strong>Datum:</strong> 17.10.2014</p>
    <p>Možnost skrytí novinek na úvodní stránce. Nové novinky se zobrazí opět s novou verzí.</p>
    <p>Do navigace přidána sekce "Novinky".</p>
</div>

<div class="ui-body ui-body-a">
    <h3>Verze 1.2.4</h3>
    <p><strong>Datum:</strong> 15.10.2014</p>
    <p>Možnost uložení formuláře jako vyhledávače v prohlížeči.</p>
    <p>Možnost odkazování na výsledek hledání přes URL.</p>
    <p>Upravení vzhledu pro větší displaye.</p>
    <p>Doplněny podmínky používání webu.</p>
    <p>Klávesová zkratka pro přechod do vyhledávacího pole.</p>
    <p>Více o novinkách v&nbsp;sekci <a href="<?php echo $this->baseUrl('/info/tips') ?>">tipy a triky</a>.</p>
</div>

<div class="ui-body ui-body-a">
    <h3>Verze 1.2.3</h3>
    <p><strong>Datum:</strong> 2.10.2014</p>
    <p>Vylepšení trackování přes GA. MtGiM JSON API.</p>
</div>

<div class="ui-body ui-body-a">
    <h3>Verze 1.2.2</h3>
    <p><strong>Datum:</strong> 26.7.2014</p>
    <p>Vylepšeno zobrazování edic pro e-shop Černý Rytíř. Zaveden changelog. Drobné grafické opravy.</p>
</div>

<div class="ui-body ui-body-a">
    <h3>Verze 1.2.0</h3>
    <p><strong>Datum:</strong> 18.7.2014</p>
    <p>Přidána možnost zobrazit obrázek karty.</p>
</div>

<div class="ui-body ui-body-a">
    <h3>Verze 1.1.2</h3>
    <p><strong>Datum:</strong> 10.7.2014</p>
    <p>Přidáno vyhledávání v obchodě rishada.cz.</p>
</div>

<div class="ui-body ui-body-a">
    <h3>Verze 1.1.0</h3>
    <p><strong>Datum:</strong> 2.7.2014</p>
    <p>Přidáno vyhledávání v dalších obchodech. Konkrétně mysticshop.cz a najda.cz.</p>
</div>

<div class="ui-body ui-body-a">
    <h3>Verze 1.0.4</h3>
    <p><strong>Datum:</strong> 12.6.2014</p>
    <p>Pouze bugfixy.</p>
</div>

<div class="ui-body ui-body-a">
    <h3>Verze 1.0.0</h3>
    <p><strong>Datum:</strong> 2.6.2014</p>
    <p>První ostrá verze aplikace.</p>
</div>
