<h2>Podmínky užívání</h2>

<div data-role="collapsible">
    <h4>Obecná ustanovení</h4>

    <p>Doména <a href="http://mtgim.cz">mtgim.cz</a> i&nbsp;veškerý její obsah jsou výlučným vlastnictvím autora.</p>
    <p>Je zakázáno využívání aplikace k&nbsp;automatizovanému získávání dat z&nbsp;obchodů
        jež jsou v&nbsp;aplikaci zahrnuty.</p>
    <p>Je zakázáno využívat aplikaci k&nbsp;jiným účelům, než ke&nbsp;kterým je určena.</p>
    <p>V&nbsp;případě objevení chyby je uživatel povinen tuto chybu neprodleně nahlásit provozovateli pomocí
        <a href="<?php echo $this->baseUrl('/index/contact') ?>">Kontaktního formuláře</a>.
    </p>
    <p>Provozovatel nezodpovídá za&nbsp;zobrazované výsledky vyhledávání.</p>
</div>

<div data-role="collapsible">
    <h4>Prohlášení o&nbsp;používání souborů cookies</h4>

    <p>Aplikace pro&nbsp;svoji činnost používá soubory cookies.</p>
    <p>
        Co jsou soubory cookies, můžete nalézt například
        <a href="http://cs.wikipedia.org/wiki/HTTP_cookie" class="external">zde</a>.
    </p>
    <p>Aplikace používá vlastní cookies pro&nbsp;identifikaci uživatele v&nbsp;rámci aplikace a
        uložení jeho preferencí.
    </p>
    <p>
        Aplikace dále používá cookies třetích stran za&nbsp;účelem monitorování akcí uživatelů a
        trendů při&nbsp;používání aplikace. Tato data slouží jako podklad k&nbsp;určení
        směru následného vývoje a propagace aplikace.
    </p>
    <p>Pokud uživatel nesouhlasí s&nbsp;poskytováním dat pomocí cookies, musí tuto aplikaci neprodleně opustit.</p>
    <p>
        Upozornění na&nbsp;úvodní stránce aplikace lze skrýt stiskem tlačítka "Souhlasím".
    </p>
    <p>Pokud má uživatel vypnuté ukládání souborů cookies, nemusí některé funkce aplikace fungovat správně.</p>
</div>
