<h2>Podmínky užívání</h2>

<div data-role="collapsible">
    <h4>Obecná ustanovení</h4>
    <ul>
        <li>Doména <a href="http://mtgim.cz">mtgim.cz</a> i&nbsp;veškerý její obsah jsou výlučným vlastnictvím autora.</li>
        <li>Je zakázáno využívání aplikace k&nbsp;automatizovanému získávání dat z&nbsp;obchodů
            jež jsou v&nbsp;aplikaci zahrnuty.</li>
        <li>Je zakázáno využívat aplikaci k&nbsp;jiným účelům, než ke&nbsp;kterým je určena.</li>
        <li>V&nbsp;případě objevení chyby je uživatel povinen tuto chybu neprodleně nahlásit provozovateli pomocí
            <a href="<?php echo $this->baseUrl('/index/contact') ?>">Kontaktního formuláře</a>.
        </li>
        <li>Provozovatel nezodpovídá za zobrazované výsledky vyhledávání.</li>
    </ul>
</div>

<div data-role="collapsible">
    <h4>Prohlášení o&nbsp;používání souborů cookies</h4>
    <ul>
        <li>Aplikace pro&nbsp;svoji činnost používá soubory cookies.</li>
        <li>
            Co jsou soubory cookies, můžete nalézt například
            <a href="http://cs.wikipedia.org/wiki/HTTP_cookie" class="external">zde</a>.
        </li>
        <li>
            Aplikace používá vlastní cookies pro&nbsp;identifikaci uživatele v&nbsp;rámci aplikace
            a uložení jeho preferencí.
        </li>
        <li>
            Aplikace používá cookies třetích stran za&nbsp;účelem monitorování akcí uživatelů a
            trendů při&nbsp;používání aplikace. Tato data slouží jako podklad k&nbsp;určení
            směru následného vývoje a propagace aplikace.
        </li>
        <li>
            Pokud uživatel nesouhlasí s&nbsp;poskytováním dat pomocí cookies, musí tuto aplikaci neprodleně opustit.
        </li>
        <li>
            Upozornění na&nbsp;úvodní stránce aplikace lze srýt stiskem tlačítka "souhlasím".
        </li>
    </ul>
</div>
