<p>Na této stránce naleznete tipy pro pohodlnější používání aplikace.
    Detail tipu si zobrazíte kliknutím na příslušný nadpis.
</p>

<div data-role="collapsible">
    <h4>Spouštěč - Android</h4>
    <ol>
        <li>Otevřete si úvodní <a href="<?php $this->baseUrl('/'); ?>" >stránku aplikace</a>.</li>
        <li>Stiskněte talčítko pro&nbsp;vyvolání <strong>menu</strong>. Obvykle bývá umístěno vpravo pod&nbsp;displayem.</li>
        <li>Zvolte "<strong>Uložit do&nbsp;záložek</strong>".</li>
        <li>V&nbsp;nabídce "<strong>Přidat do&nbsp;složky</strong>" zvolte "<strong>Úvodní obrazovka</strong>".</li>
        <li>Nyní můžete aplikace pouštět přímo ze&nbsp;své plochy.</li>
    </ol>
</div>

<div data-role="collapsible">
    <h4>Horní panel</h4>
    <ul>
        <li>Díky hornímu panelu můžete vyhledávat karty z&nbsp;libovolné stránky aplikace.</li>
        <li>Logo vlevo slouží také k&nbsp;přechodu na&nbsp;úvodní stránku.</li>
        <li>Pravé logo vyvolává postranní panel s&nbsp;navigací.</li>
    </ul>
</div>

<div data-role="collapsible">
    <h4>Výsledky hledání</h4>
    <ul>
        <li>Výsledky hledání jsou vždy omezeny na jeden obchod. Název aktuálního obchodu je zobrazen v prvním tlačítku na stránce.</li>
        <li>Změnit obchod lze kliknutím na tlačítko s právě zobrazeným obchodem a vybráním jiného obchodu ze seznamu.</li>
        <li>Pro kažadý obchod lze zvolit, zda-li chcete zobrazit pouze not-foil (obyčejné), nebo pouze foil karty.</li>
        <li>
            Pro kartu v seznamu lze zobrazit její obrázek kliknutím na tlačítko v pravé části.
            <ul>
                <li>
                    Karta je hledána podle zobrazeného názvu. Pokud obchod obsahuje v názvu karty nějaké další informace
                    (například "emblem" nebo "token") nemusí se obrázek zobrazit vůbec.
                </li>
                <li>
                    Na zlepšování zobrazení těchto případů průbežně pracujeme.
                </li>
                <li>Pro zobrazování obrázků karet je použit projekt <a class="external" href="http://mtgimage.com/">MTG Image</a>.</li>
            </ul>
        </li>
    </ul>
</div>

<div data-role="collapsible">
    <h4>Skrytí panelů</h4>
    <ul>
        <li>
            Na dlouhých stránkách (obsah stránky se nevejde na jeden monitor vašeho zařízení) lze skrýt vrchní a spodní
            panel aplikace a to jednoduchým kliknutím kdekoliv do aplikace. Tedy samozřejmě s výjimkou tlačítek a odkazů.
        </li>
        <li>
            Skryté panely lze stejným způsobem zobrazit.
        </li>
    </ul>
</div>
