<div data-role="panel" id="menubar" data-position="right" data-animate="true" data-position-fixed="true" data-display="overlay">
    <ul data-role="listview" data-theme="b">
        <li data-role="list-divider" id="menubar-header">
            <a href="#" class="ui-btn ui-icon-delete ui-btn-icon-notext" data-rel="close">Zavřít</a>
        </li>
        <li><a class="ui-btn ui-btn-icon-left ui-icon-home" href="<?php echo $this->baseUrl('/') ?>">Úvod</a></li>
        <li><a class="ui-btn ui-btn-icon-left ui-icon-info" href="<?php echo $this->baseUrl('/info/about') ?>">O aplikaci</a></li>
        <li><a class="ui-btn ui-btn-icon-left ui-icon-star" href="<?php echo $this->baseUrl('/info/tips') ?>">Tipy a triky</a></li>
        <li><a class="ui-btn ui-btn-icon-left ui-icon-edit" href="<?php echo $this->baseUrl('/index/contact') ?>">Kontakt</a></li>
        <li><a class="ui-btn ui-btn-icon-left ui-icon-alert" href="<?php echo $this->baseUrl('/info/terms') ?>">Podmínky</a></li>
    </ul>
</div>