<?php if ($this->showCookiesInfo): ?>
    <div id="cookies-accept-block" class="ui-body ui-body-b ui-corner-all warning-box ui-overlay-shadow">
        <p>Aplikace používá cookies. Pokud nesouhlasíte s používáním souborů cookies, opusťte tuto stránku</p>
        <p>Více o používání cookies naleznete na stránce "Podmínky používání webu".</p>
        <p class="ui-mini">
            <a class="ui-btn ui-btn-a ui-btn-icon-left ui-icon-alert ui-corner-all"
               href="<?php echo $this->baseUrl('/info/terms') ?>">Podmínky užívání</a>
            <a class="ui-btn ui-btn-icon-left ui-icon-check ui-corner-all"
               href="<?php echo $this->baseUrl('/?cookieAccept=1') ?>" id="cookies-agree">Souhlasím</a>
        </p>
    </div>
<?php endif; ?>

<form id="searchform" method="GET" action="<?php echo $this->baseUrl('/index/find') ?>">
    <input type="search" name="cardname" id="cardname" placeholder="Karta" value="" tabindex="0" accesskey="f" />
    <input type="submit" name="find" id="find" value="Hledej" data-transition="slide" data-icon="search" />
</form>

<?php if ($this->showNews): ?>
    <div id="news-block" data-role="collapsible" data-collapsed="false">
        <h4>Novinky v&nbsp;aplikaci
            <a class="ui-btn ui-btn-icon-notext ui-icon-delete ui-btn-inline ui-btn-corner-all ui-btn-right"
               href="<?php echo $this->baseUrl('/?hideNews=1') ?>" id="news-hide-1">Skrýt</a>
        </h4>
        <ul>
            <li>Možnost skrytí tohoto boxu. Nové novinky se zobrazí opět s novou verzí.</li>
            <li>Nyní je možné uložit si výsledek hledání do&nbsp;záložek, nebo poslat odkaz na&nbsp;výsledek kamarádovi.</li>
            <li>Nově je možné označit pole hledání karty jako vyhledávač (Chrome, Firefox).</li>
            <li>Lze použít klávesovou zkratku <strong>Alt + f</strong> pro&nbsp;přechod do&nbsp;vyhledávacího pole. Podrobněji na stránce tipy a triky.</li>
        </ul>

        <p>Více informací o novinkách naleznete v&nbsp;sekci tipy a triky.</p>

        <p class="ui-mini">
            <a class="ui-btn ui-btn-b ui-btn-icon-left ui-icon-delete ui-corner-all"
               href="<?php echo $this->baseUrl('/?hideNews=1') ?>" id="news-hide-2">Skrýt</a>
        </p>
    </div>
<?php endif; ?>

<div class="front-info">
    <p>Aplikace slouží pro&nbsp;vyhledávání karet v&nbsp;internetových MtG obchodech z&nbsp;pohodlí vašeho mobilu.</p>
    <p>Můžete vyhledávat v těchto obchodech:</p>
    <ul>
        <li><a class="external" href="http://www.cernyrytir.cz">www.cernyrytir.cz</a></li>
        <li><a class="external" href="http://www.mysticshop.cz">www.mysticshop.cz</a></li>
        <li><a class="external" href="http://www.najada.cz">www.najada.cz</a></li>
        <li><a class="external" href="http://www.rishada.cz">www.rishada.cz</a></li>
    </ul>

    <p class="ui-mini" >
        <a class="ui-btn ui-btn-icon-left ui-icon-star ui-corner-all"
           href="<?php echo $this->baseUrl('/info/tips') ?>"
           data-transition="slide"
        >
            Tipy a triky
        </a>
    </p>
</div>
