<!DOCTYPE html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <title><?php echo $this->appName ?></title>

    <link rel="shortcut icon" href="<?php echo $this->baseUrl('/images/icons/favicon.ico') ?>" type="image/x-icon">

    <?php echo $this->PartialLoop('partials/meta.phtml', $this->meta) ?>
    <?php echo $this->PartialLoop('partials/og.phtml', $this->og) ?>
    <?php echo $this->PartialLoop('partials/appleTouch.phtml', $this->apple) ?>

    <meta property="fb:app_id" content="<?php echo $this->fbAppId ?>">

    <?php echo $this->headLink() ?>
</head>
<body>
<div id="fb-root"></div>
<div data-role="page" id="<?php echo $this->pageId ?>" data-theme="a">
    <?php echo $this->partial('partials/topbar.phtml', $this) ?>

    <div role="main" class="ui-content">
        <?php echo $this->layout()->content; ?>
    </div>

    <?php echo $this->partial('partials/bottombar.phtml', $this) ?>
    <?php echo $this->partial('partials/menubar.phtml', $this) ?>
</div>
<?php echo $this->headScript() ?>
</body>
</html>
