<h2>Účel aplikace</h2>
<p>Aplikace slouží pro&nbsp;vyhledávání karet v&nbsp;internetových MtG obchodech z&nbsp;pohodlí vašeho mobilu.</p>
<p>Přes aplikaci není možné karty zakoupit. Slouží pouze pro&nbsp;zjednodušení hledání ceny karet.</p>
<p>Můžete vyhledávat v těchto obchodech:</p>
<ul>
    <li><a href="http://www.cernyrytir.cz">www.cernyrytir.cz</a></li>
    <li><a href="http://www.mysticshop.cz">www.mysticshop.cz</a></li>
    <li><a href="http://www.najada.cz">www.najada.cz</a></li>
    <li><a href="http://www.rishada.cz">www.rishada.cz</a></li>
</ul>

<h3>Technická omezení</h3>
<p>Maximální počet zobrazených výsledků hledání v jednotlivých obchodech je omezen.</p>
<ul>
    <li>Pro obchody <a href="http://www.cernyrytir.cz">www.cernyrytir.cz</a> a <a href="http://www.najada.cz">www.najada.cz</a> je omezení na 30 výsledků.</li>
    <li>Pro obchody <a href="http://www.mysticshop.cz">www.mysticshop.cz</a> a <a href="http://www.rishada.cz">www.rishada.cz</a> je omezení na 50 výsledků.</li>
</ul>
<p>
    Některé obchody se mohou načítat pomalu, nebo vůbec. Data od obchodů nemáme uložená ve vlastní databázi,
    ale získáváme je na dotaz přímo od obchodů. Pokud má daný obchod pomalou odezvu, nebo jeho stránky nefungují,
    bude tento problém i v naší aplikaci.
</p>

<h2>Motivace</h2>
<p>
    MtG obchody v&nbsp;České republice příliš nedbají na&nbsp;komfort uživatelů chytrých telefonů. Níže si&nbsp;můžete prohlédnout,
    jak vypadá obchod <a href="http://www.cernyrytir.cz">www.cernyrytir.cz</a> v&nbsp;mobilním zařízení. Nebo pokud najdete
    odvahu, klikněte na&nbsp;jeden z&nbsp;odkazů na&nbsp;tento obchod a zkuste stránku použít pro&nbsp;vyhledání libovolné karty.
</p>

<img src="<?php echo $this->baseUrl('/images/cr-screenshot.png') ?>" alt="Obrázek: Náhled obchodu" title="Náhled obchodu" />

<p>Tato aplikace má za cíl Vám toto hledání usnadnit pomocí minimalistického a přehledného rozhraní.</p>

<h2>O aplikaci</h2>
<p><strong>Autor:</strong> Jiří Bažant</p>
<p><strong>Testování:</strong> Filip Rosocha</p>
<p><strong>Současná verze aplikace:</strong> <?php echo $this->appVersion ?></p>

<h3>Použité technologie</h3>
<ul>
    <li><a href="http://framework.zend.com/">Zend framework</a></li>
    <li><a href="http://jquerymobile.com/">jQuery Mobile</a></li>
    <li><a href="http://mtgimage.com/">MTG Image</a></li>
</ul>

<p><a href="<?php echo $this->baseUrl('/info/changelog') ?>">Changelog</a></p>
<!--p>Všechna práva vyhrazena.</p-->
