<h2>Účel aplikace</h2>
<p>Aplikace slouží pro&nbsp;vyhledávání karet v&nbsp;obchodě <a href="http://www.cernyrytir.cz">www.cernyrytir.cz</a> z&nbsp;pohodlí vašeho mobilu.</p>

<p>Přes aplikaci není možné karty zakoupit. Slouží pouze pro&nbsp;zjednodušení hledání ceny karet.</p>

<h2>Motivace</h2>
<p>
    MtG obchody v&nbsp;České republice příliš nedbají na&nbsp;komfort uživatelů chytrých telefonů. Níže si&nbsp;můžete prohlédnout,
    jak vypadá obchod <a href="http://www.cernyrytir.cz">www.cernyrytir.cz</a> v&nbsp;mobilním zařízení. Nebo pokud najdete
    odvahu, klikněte na&nbsp;jeden z&nbsp;odkazů na&nbsp;tento obchod a zkuste stránku použít pro&nbsp;vyhledání libovolné karty.
</p>

<img src="<?php echo $this->baseUrl('/images/cr-screenshot.png') ?>" alt="Obrázek: Náhled obchodu" title="Náhled obchodu" />

<p>Tato aplikace má za cíl Vám toto hledání usnadnit pomocí minimalistického a přehledného rozhraní.</p>

<h2>O aplikaci</h2>
<p><strong>Autor:</strong> Jiří Bažant</p>
<p><strong>Testování:</strong> Filip Rosocha</p>
<!--p>Všechna práva vyhrazena.</p-->
<p><strong>Současná verze aplikace:</strong> <?php echo $this->appVersion ?></p>