<table>
    <tr>
        <th>Datum</th>
        <th>Verze</th>
        <th>Poznámky</th>
    </tr>
    <tr>
        <td>26.7.2014</td>
        <td>1.2.2</td>
        <td>Vylepšeno zobrazování edic pro e-shop Černý Rytíř. Zaveden changelog. Drobné grafické opravy.</td>
    </tr>
    <tr>
        <td>18.7.2014</td>
        <td>1.2.0</td>
        <td>Přidána možnost zobrazit obrázek karty.</td>
    </tr>
    <tr>
        <td>10.7.2014</td>
        <td>1.1.2</td>
        <td>Přidáno vyhledávání v obchodě rishada.cz.</td>
    </tr>
    <tr>
        <td>2.7.2014</td>
        <td>1.1.0</td>
        <td>Přidáno vyhledávání v dalších obchodech. Konkrétně mysticshop.cz a najda.cz.</td>
    </tr>
    <tr>
        <td>12.6.2014</td>
        <td>1.0.4</td>
        <td>Pouze bugfixy.</td>
    </tr>
    <tr>
        <td>?</td>
        <td>1.0.0</td>
        <td>První ostrá verze aplikace.</td>
    </tr>
</table>