<p>Na této stránce naleznete tipy pro pohodlnější používání aplikace.
    Detail tipu si zobrazíte kliknutím na příslušný nadpis.
</p>

<div data-role="collapsible">
    <h4>Spouštěč - Android</h4>
    <ol>
        <li>Otevřete si úvodní <a href="<?php $this->baseUrl('/'); ?>" >stránku aplikace</a>.</li>
        <li>Stiskněte talčítko pro&nbsp;vyvolání <strong>menu</strong>. Obvykle bývá umístěno vpravo pod&nbsp;displayem.</li>
        <li>Zvolte "<strong>Uložit do&nbsp;záložek</strong>".</li>
        <li>V&nbsp;nabídce "<strong>Přidat do&nbsp;složky</strong>" zvolte "<strong>Úvodní obrazovka</strong>".</li>
        <li>Nyní můžete aplikace pouštět přímo ze&nbsp;své plochy.</li>
    </ol>
</div>

<div data-role="collapsible">
    <h4>Horní panel</h4>
    <ul>
        <li>Díky hornímu panelu můžete vyhledávat karty z&nbsp;libovolné stránky aplikace.</li>
        <li>Logo vlevo slouží také k&nbsp;přechodu na&nbsp;úvodní stránku.</li>
        <li>Pravé logo vyvolává postranní panel s&nbsp;navigací.</li>
    </ul>
</div>